pipeline {
    
    agent any 

    tools {
        maven 'Maven 3.6.1' 
    }

    
    stages {
        stage('build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compile worker app'
                dir('worker'){
                sh 'mvn compile'
                }
            }
        }
        stage('test') {
           when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app'
                dir('worker'){
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

                }
            }
        }
        
        
    }
        post { 
        always { 
            echo 'Pipeline for worker is complete...'
        }
        failure {
           slackSend (channel: "testing-jenkins-cicd", color: '#FF0000', message: "FAILED: Job ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
       }
        success {
           slackSend (channel: "testing-jenkins-cicd", color: '#00ff59', message: "SUCCESS: Job ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
       }
    }
}